[tool.poetry]
name = "bertlv"
version = "0.1.0"
description = "Library for BER TLV (tag-length-value) en-/decoding."
license = "BSD-3-Clause"
authors = ["Philip Schömig <philip.schoemig@posteo.de>"]
packages = [
    { include = "bertlv", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
tox = "^3.14.5"
bump2version = "^1.0.0"
black = "^19.10b0"

[tool.poetry.scripts]
bertlv = 'bertlv.__main__:main'

[tool.black]
line-length = 88
target-version = ["py36"]
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
