name: Coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.3
    - name: Set up cache
      uses: actions/cache@v2.1.4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install -E basis
    - name: Generate coverage report
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 79982f5a1d5cce202bcdc009fedfbb9fc9f391da090c0f85f04fabd93d71ddb3
      with:
        coverageCommand: poetry run tox -e py -- --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
